blog/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from .views import IndexView, BlogDetailView, CategoryView, TagView, AboutMeView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^about/$', AboutMeView.as_view(), name='about'),
    url(r'^article/(?P<article_id>\d+)$', BlogDetailView.as_view(), name='detail'),
    url(r'^category/(?P<cate_id>\d+)$', CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', TagView.as_view(), name='tag'),
]

handrixite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
]

blog/models.py
# -*- coding:utf-8 -*-

from django.db import models


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )

    title = models.CharField(max_length=80)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    body = models.TextField()
    author = models.CharField(max_length=20)
    photo = models.URLField(blank=True, default="http://placehold.it/900x300")
    create_data = models.DateTimeField(auto_now_add=True)

    category = models.ForeignKey('Category', verbose_name='分类', null=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)
    pass

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_data']


class Category(models.Model):
    name = models.CharField('类名', max_length=20)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('标签名', max_length=20)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

blog/views.py
# -*- coding:utf-8 -*-

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from . import models
import markdown2


class IndexView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        article_list = models.Article.objects.all()
        return article_list
        pass

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = models.Category.objects.all().order_by('name')
        kwargs['tag_list'] = models.Tag.objects.all().order_by('name')
        return super(IndexView, self).get_context_data(**kwargs)
        pass
    pass


class BlogDetailView(DetailView):
    template_name = "blog/detail.html"
    context_object_name = "article"
    pk_url_kwarg = 'article_id'

    def get_queryset(self):
        article_list = models.Article.objects.all()
        return article_list
        pass

    def get_object(self, queryset=None):
        obj = super(BlogDetailView, self).get_object()
        obj.body = markdown2.markdown(obj.body, extras=['fenced-code-blocks'], )
        return obj
        pass
    pass


class CategoryView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        article_list = models.Article.objects.filter(category=self.kwargs['cate_id'], status='p')
        for article in article_list:
            article.body = article.body
        return article_list
        pass

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = models.Category.objects.all().order_by('name')
        return super(CategoryView, self).get_context_data(**kwargs)
        pass
    pass


class TagView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        article_list = models.Article.objects.filter(tags=self.kwargs['tag_id'], status='p')
        for article in article_list:
            article.body = article.body
        return article_list
        pass

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = models.Tag.objects.all().order_by('name')
        return super(TagView, self).get_context_data(**kwargs)
        pass
    pass


class AboutMeView(TemplateView):
    template_name = "blog/about.html"

blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} handrix's site {% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/blog-home.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}">handrix's blog</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'blog:index' %}">首页</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:about' %}">About Me</a>
                    </li>
                    <li>
                        <a href="#">Chat</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block content %}{% endblock %}
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; zequnfeng's blog 2016</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

blog/templates/blog/about.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-12">
                    <h1 class="page-title">关于我</h1>
                    <article class="post">
                        <div class="entry-content clearfix">
                            <figure class="img-responsive-center">
                                <img class="img-responsive" src="{% static 'img/me.pnq' %}" alt="Developer Image">
                            </figure>
                            <p>略</p>
                            <div class="height-40px"></div>
                            <h2>社交账号</h2>
                            <br/>
                            <br/>
                            <div>
                                <a href="#"><i class="fa fa-weibo fa-3x" aria-hidden="true"></i></a>
                                &nbsp&nbsp&nbsp&nbsp&nbsp
                                <a href="#"><i class="fa fa-weixin fa-3x" aria-hidden="true"></i></a>
                                &nbsp&nbsp&nbsp&nbsp&nbsp
                                <a href="#"><i class="fa fa-google-plus fa-3x" aria-hidden="true"></i></a>
                                &nbsp&nbsp&nbsp&nbsp&nbsp
                                <a href="#"><i class="fa fa-github fa-3x" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </article>
                </main>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends "base.html" %}

{% block content %}
{{ article.body |safe }}
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
<div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">

        <h1 class="page-header">
            博客列表
            <small></small>
        </h1>

        <!-- Blog Post -->
        {% load paginate_tags %}
        {% paginate article_list 2 %}
        {% for article in article_list %}
        <h3>
            <a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a>
        </h3>
        <p class="lead">
            by <a href="#">{{ article.author }}</a>
        </p>
        <p><span class="glyphicon glyphicon-time"></span> {{ article.create_data|date:"Y / m / d" }}</p>
        <hr>
        <img class="img-responsive" src="{{ article.photo }}" alt="">
        <hr>
        <p>{{ article.body }}</p>
        <a class="btn btn-primary" href="{% url 'blog:detail' article.id %}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
        <hr>
        {% endfor %}

        <!-- Pager -->
        {% include 'blog/pagination.html' %}

    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

        <!-- Blog Search Well -->
        <div class="well">
            <h4>Blog Search</h4>
            <div class="input-group">
                <input type="text" class="form-control">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <span class="glyphicon glyphicon-search"></span>
                </button>
                </span>
            </div>
            <!-- /.input-group -->
        </div>

        <!-- Blog Categories Well -->
        <div class="well">
            <h4>分类</h4>
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled">
                        {% for category in category_list %}
                        <li><a href="{% url 'blog:category' category.pk %}">{{ category }}</a>
                        </li>
                        {% endfor %}
                        <h4>标签</h4>
                        <div class="row">
                        <div class="col-lg-6">
                        <ul class="list-unstyled">
                        {% for tag in tag_list %}
                           <li><a href="{% url 'blog:tag' tag.pk %}">{{ tag }}</a>
                           </li>
                        {% endfor %}
                    </ul>
                </div>
                </div>
                    </ul>
                </div>
                <!-- /.col-lg-6 -->
            </div>
            <!-- /.row -->
        </div>

        <!-- Side Widget Well -->
        <div class="well">
            <h4>最近更新</h4>
        </div>

    </div>

</div>
<!-- /.row -->

<hr>
{% endblock %}

blog/templates/blog/pagination.html
<div class="pager">
    {% if article_list.has_previous %}
        <li class="previous"><a class="previous-page" href="?page={{ article_list.previous_page_number }}">
            &larr; Older
        </a></li>
    {% endif %}

    {% if first_page == current_page %}
        <li><span class="first-page current">1</span></li>
    {% else %}
        <li><a href="?page=1" class="first-page">1</a></li>
    {% endif %}

    {% if pages_first > 2 %}
        <span>...</span>
    {% endif %}

    {% for page in pages %}
        {% if page == current_page %}
            <li><span class="current">{{ page }}</span></li>
        {% else %}
            <li><a href="?page={{ page }}">{{ page }}</a></li>
        {% endif %}
    {% endfor %}

    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <li><span class="current">{{ last_page }}</span></li>
        {% else %}
            <li><a href="?page={{ last_page }}">{{ last_page }}</a></li>
        {% endif %}
    {% endif %}

    {% if article_list.has_next %}
        <li class="next"><a class="next-page" href="?page={{ article_list.next_page_number }}">
            Newer &rarr;
        </a></li>
    {% endif %}
</div>